"use client";

import { useState } from "react";

// Uses the native share sheet on phones (navigator.share); falls back to
// copying the text on desktop browsers that don't support it. When an
// imageUrl is given (see /api/share-card) and the device can share files,
// the share includes a branded card image — which is what actually looks
// like something when it lands in a group chat or a story. Still no
// external service: the card is generated by the app itself.
export default function ShareButton({
  text,
  label = "Share",
  className = "",
  imageUrl,
}: {
  text: string;
  label?: string;
  className?: string;
  imageUrl?: string;
}) {
  const [copied, setCopied] = useState(false);

  async function handleShare() {
    if (typeof navigator !== "undefined" && "share" in navigator) {
      // Best case: share the generated card as a real image file.
      if (imageUrl && "canShare" in navigator) {
        try {
          const res = await fetch(imageUrl);
          if (res.ok) {
            const blob = await res.blob();
            const file = new File([blob], "forge.png", { type: "image/png" });
            if (navigator.canShare({ files: [file] })) {
              await navigator.share({ files: [file], text, title: "Forge" });
              return;
            }
          }
        } catch {
          // Card fetch failed or share cancelled — fall through to text.
        }
      }
      try {
        await navigator.share({ text, title: "Forge" });
        return;
      } catch {
        // User cancelled or share failed — fall back to clipboard below.
      }
    }
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Clipboard blocked — nothing more we can do.
    }
  }

  return (
    <button
      type="button"
      onClick={handleShare}
      className={
        "press rounded-lg border border-line bg-surface px-3 py-2 text-sm font-bold transition hover:border-forge/50 " +
        className
      }
    >
      {copied ? "Copied! ✅" : `📤 ${label}`}
    </button>
  );
}
